<?php
/**
 * @file
 * Archivo para empezar a programar con Drupal
 */

/**
 * Implementa hook_menu().
 */
function saludar_menu() {

	// Pagina del modulo
	$items['saludar/hola-mundo'] = array(
		'title' => 'Saludar',
		'page callback' => 'saludar_hola_mundo',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	// Configuracion administrativa del modulo
	$items['admin/config/content/saludar'] = array(
			'title' => 'Saludar',
			'description' => 'Configurar las opciones para el saludo.',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('saludar_configuracion'),
			'access arguments' => array('administer site configuration'),
			'file' => 'saludar.admin.inc',
	);
	
	return $items;
}

/**
 * Implementa hook_theme().
 */
function saludar_theme() {
	return array(
		'saludar_hola_mundo' => array(
			'template' => 'saludar-hola-mundo',
		),
	);
}

/**
 * Implementa hook_block_info().
 */
function saludar_block_info() {
	$blocks['hola_mundo'] = array(
		'info' => 'Bloque para Hola Mundo',
	);
	return $blocks;
}

/**
 * Implementa hook_block_view().
 */
function saludar_block_view($delta = '') {
	switch ($delta) {
		case 'hola_mundo':
			$block['content'] = saludar_hola_mundo();
			return $block;
	}
	break;
}

/**
 * Implementa hook_user_login().
 */
// function saludar_user_login(&$edit, $account) {
// 	drupal_set_message("Hola " . $account->name);
// }

/**
 * Acción de drupal que saluda al usuario.
 */
// function saludar_usuario_action() {
// 	$message = "¡Bienvenido!";
// 	if (user_is_logged_in()) {
// 		$message = "Hola " . $GLOBALS['user']->name;
// 	}
// 	drupal_set_message($message);
// }

/**
 * Implementa hook_action_info().
 */
function saludar_usuario_action() {
	drupal_set_message("Hola " . format_username($GLOBALS['user']));
}

/**
 * Callback que implementa la página: saludar/hola-mundo.
 */
function saludar_hola_mundo() {
	$fecha = time ();
  $variables = array(
    'saludo'	=> variable_get('saludar_saludo', 'Hola Mundo'),
  	'fecha'		=> date("h:i:s", $fecha),
  );
  return theme('saludar_hola_mundo', $variables);
}

